// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
 
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DALProject.Data.Contexts
{
    public partial interface IHMSdbcontextProcedures
    {
        Task<int> sp_DeleteActiveSubstanceAsync(int? ActiveSubstancesId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
